[env:esp32-s3-eth]
platform = symlink://C:/Users/ashhi/.platformio/platforms/espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
extra_scripts = pre:scripts/load_env.py
platform_packages =
    framework-arduinoespressif32 @ symlink://C:/Users/ashhi/.platformio/packages/framework-arduinoespressif32
    framework-arduinoespressif32-libs @ symlink://C:/Users/ashhi/.platformio/packages/framework-arduinoespressif32-libs
    toolchain-xtensa-esp32s3 @ symlink://C:/Users/ashhi/.platformio/packages/toolchain-xtensa-esp-elf
    tool-esptoolpy @ symlink://C:/Users/ashhi/.platformio/packages/tool-esptoolpy
    tool-esp_install @ symlink://C:/Users/ashhi/.platformio/packages/tool-esp_install

# Compiler flags
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

# Libraries required
lib_deps =
    ArduinoJson@^6.21.0
    Adafruit NeoPixel@^1.10.7
    ESP8266 and ESP32 OLED driver for SSD1306@^4.4.0
    WebServer
    DNSServer
    HTTPClient
    WiFiClientSecure
    Preferences
    ETH

# Monitor settings
monitor_filters = esp32_exception_decoder
